services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ged_app
    restart: unless-stopped
    volumes:
      - .env:/var/www/.env
      - storage_data:/var/www/storage
    networks:
      - ged_network

  nginx:
    image: nginx:1.25-alpine
    container_name: ged_nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
      - storage_data:/var/www/storage
    depends_on:
      - app
    networks:
      - ged_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ged.rule=Host(`ged.abac-admin.cloud`)"
      - "traefik.http.routers.ged.entrypoints=websecure"
      - "traefik.http.routers.ged.tls.certresolver=letsencrypt"
      - "traefik.http.services.ged.loadbalancer.server.port=80"

volumes:
  storage_data:

networks:
  ged_network:
    driver: bridge